.travis.yml, build.sbt, core/src/main/scala/it/parttimeteam/Rank.scala, core/src/main/scala/it/parttimeteam/Suit.scala, core/src/test/scala/it/parttimeteam/RankSuite.scala, core/src/test/scala/it/parttimeteam/SuitSuite.scala, travis-scripts/deploy_to_pages.sh
Developed the suit core entity. @pagno4 can you review this?
=> Suit core entity

.travis.yml, core/src/main/scala/it/parttimeteam/Card.scala, travis-scripts/deploy_to_pages.sh
Some improvements to travis jobs.
=> Travis updates

core/src/main/scala/it/parttimeteam/Rank.scala, core/src/test/scala/it/parttimeteam/RankSuite.scala, core/src/test/scala/it/parttimeteam/SuitSuite.scala, travis-scripts/deploy_to_pages.sh
Added property testing for some core entities.
=> Suit property test

core/src/main/scala/it/parttimeteam/Card.scala, core/src/main/scala/it/parttimeteam/Rank.scala, core/src/main/scala/it/parttimeteam/Suit.scala, core/src/test/scala/it/parttimeteam/CardSuite.scala, core/src/test/scala/it/parttimeteam/RankSuite.scala, core/src/test/scala/it/parttimeteam/SuitSuite.scala
Created card entity. After this, we can start modeliing all other core entities.
=> Card core entity

README.md, core/src/main/scala/it/parttimeteam/Card.scala, core/src/main/scala/it/parttimeteam/Deck.scala, core/src/main/scala/it/parttimeteam/Suit.scala, core/src/test/scala/SampleClassSpec.scala, core/src/test/scala/it/parttimeteam/CardSuite.scala, core/src/test/scala/it/parttimeteam/DeckSuite.scala, core/src/test/scala/it/parttimeteam/RankSuite.scala, core/src/test/scala/it/parttimeteam/SuitSuite.scala, source/index.html
Create the core entity Deck and improve other tests.
=> Deck core entity

.travis.yml
Some fix to email notification and some minor fix to stages. Anyone can merge this pr after build check.
=> Travis notif fix

commons/src/main/scala/it/parttimeteam/gamestate/PlayerGameState.scala, core/src/main/scala/it/parttimeteam/Board.scala, core/src/main/scala/it/parttimeteam/GameState.scala, core/src/main/scala/it/parttimeteam/core/GameManager.scala, core/src/main/scala/it/parttimeteam/core/cards/Card.scala, core/src/main/scala/it/parttimeteam/core/collections/Deck.scala, core/src/main/scala/it/parttimeteam/core/collections/Hand.scala, core/src/main/scala/it/parttimeteam/core/player/Player.scala, core/src/test/scala/it/parttimeteam/GameStateBoardSpec.scala, core/src/test/scala/it/parttimeteam/GameStateSpec.scala, core/src/test/scala/it/parttimeteam/core/GameManagerSuite.scala, core/src/test/scala/it/parttimeteam/core/cards/RankSuite.scala, core/src/test/scala/it/parttimeteam/core/collections/DeckSpec.scala, core/src/test/scala/it/parttimeteam/core/collections/HandSpec.scala, core/src/test/scala/it/parttimeteam/core/player/PlayerSpec.scala, project/build.properties, server/src/main/scala/it/partitimeteam/match/GameMatchActor.scala
First client core interface implementation. Missing prolog functions.
=> Client core interface implementation

.travis.yml, README.md, source/index.html
Some minor changes to main page.
=> Gh pages site

client/src/main/scala/it/parttimeteam/controller/MainControllerImpl.scala, client/src/main/scala/it/parttimeteam/controller/game/GameController.scala, client/src/main/scala/it/parttimeteam/controller/game/GameControllerImpl.scala, client/src/main/scala/it/parttimeteam/controller/startup/StartUpController.scala, client/src/main/scala/it/parttimeteam/controller/startup/StartUpControllerImpl.scala, client/src/main/scala/it/parttimeteam/model/game/GameService.scala, client/src/main/scala/it/parttimeteam/model/game/GameServiceImpl.scala, client/src/main/scala/it/parttimeteam/model/game/RemoteGameActor.scala, commons/src/main/scala/it/parttimeteam/messages/GameMessage.scala, core/src/test/scala/it/parttimeteam/GameStateSpec.scala, core/src/test/scala/it/parttimeteam/core/GameManagerSuite.scala, server/src/main/scala/it/partitimeteam/match/GameMatchActor.scala, server/src/test/scala/it/parttimeteam/match/GameStateMatchActorSpec.scala
fix GameState getP method renaming
=> Server game logic

client/src/main/scala/it/parttimeteam/controller/startup/StartUpControllerImpl.scala, commons/src/main/scala/it/parttimeteam/Constants.scala, server/src/main/resources/application.conf, server/src/main/scala/it/partitimeteam/ScalavelliServer.scala
Extract server config parameters in Constant object
=> Server config paramenters

client/src/main/scala/it/parttimeteam/controller/game/GameControllerImpl.scala, core/src/main/scala/it/parttimeteam/Board.scala, core/src/main/scala/it/parttimeteam/core/collections/CardCombination.scala, core/src/main/scala/it/parttimeteam/core/collections/Deck.scala, core/src/test/scala/it/parttimeteam/GameStateBoardSpec.scala, core/src/test/scala/it/parttimeteam/core/GameManagerSuite.scala, core/src/test/scala/it/parttimeteam/core/collections/CardCombinationSpec.scala
Add an Id to the cardcombination to better identify them.
=> Card combination refactoring

commons/src/main/scala/it/parttimeteam/entities/Player.scala, commons/src/main/scala/it/parttimeteam/messages/GameMessage.scala, server/src/main/scala/it/parttimeteam/common/GamePlayer.scala, server/src/main/scala/it/parttimeteam/common/Identifiable.scala, server/src/main/scala/it/parttimeteam/common/Player.scala, server/src/main/scala/it/parttimeteam/common/Referable.scala, server/src/main/scala/it/parttimeteam/lobby/GameLobby.scala, server/src/main/scala/it/parttimeteam/lobby/Lobby.scala, server/src/main/scala/it/parttimeteam/lobby/LobbyManager.scala, server/src/main/scala/it/parttimeteam/lobby/LobbyManagerActor.scala, server/src/main/scala/it/parttimeteam/match/GameMatchActor.scala, server/src/test/scala/it/parttimeteam/lobby/LobbyManagerSpec.scala, server/src/test/scala/it/parttimeteam/lobby/LobbySpec.scala, server/src/test/scala/it/parttimeteam/match/GameStateMatchActorSpec.scala
Moved classes used only by the server from common module to server module
=> moved server user only classes from common module into server

core/src/main/scala/it/parttimeteam/core/GameManager.scala, core/src/main/scala/it/parttimeteam/core/player/Player.scala, core/src/test/scala/it/parttimeteam/core/GameManagerSuite.scala, server/src/main/scala/it/parttimeteam/match/GameMatchActor.scala, server/src/test/scala/it/parttimeteam/match/GameStateMatchActorSpec.scala
fix missing player name in game state
=> player name added to game state

client/src/main/scala/it/parttimeteam/controller/game/GameControllerImpl.scala, client/src/main/scala/it/parttimeteam/view/game/scenes/panes/HandBar.scala, commons/src/main/scala/it/parttimeteam/Constants.scala, core/src/main/scala/it/parttimeteam/core/GameManager.scala, core/src/main/scala/it/parttimeteam/core/cards/Card.scala, core/src/main/scala/it/parttimeteam/core/collections/CardCombination.scala, core/src/main/scala/it/parttimeteam/core/collections/Hand.scala, core/src/main/scala/it/parttimeteam/core/prolog/PrologGame.scala, core/src/test/scala/it/parttimeteam/core/GameManagerSuite.scala, core/src/test/scala/it/parttimeteam/core/collections/HandSpec.scala
Some fix at comments. Renamed table cards to board cards.
=> Core game manager refactoring

core/src/main/scala/it/parttimeteam/core/collections/Hand.scala
servono per completare le funzionaltà di gioco, mancano giusto i test che potete aggiungere quando volete, anche se c'è poco da testare visto che rimandano a metodi di sort a loro volta testati quindi...
=> Hand - sort methods

client/src/main/scala/it/parttimeteam/controller/game/GameControllerImpl.scala, client/src/main/scala/it/parttimeteam/model/game/GameServiceImpl.scala
adds: 
- update combination
- pick combianation
- game service impl code refactoring
=> Client attach core functionalities

.travis.yml, build.sbt, client/build.sbt, server/build.sbt, source/index.html
Fix some CI problems, the missing release bug first and other minors.
=> Version bumping to 0.1.2

.travis.yml
=> Remove tag limitation to gh release stage.

.travis.yml
Change path to take packages to release on Github.
=> Change package's path.

client/src/main/resources/application.conf, commons/src/main/scala/it/parttimeteam/utils/CustomLogger.scala, server/src/main/resources/application.conf, server/src/main/scala/it/parttimeteam/lobby/LobbyManager.scala, server/src/main/scala/it/parttimeteam/lobby/LobbyManagerActor.scala, server/src/main/scala/it/parttimeteam/match/GameMatchManagerActor.scala
=> Server logs

.travis.yml
=> Travis tag commits before deploy.

.travis.yml
Surprise! Another PR for Travis!
=> Travis tag commit

core/src/main/resources/rules.pl
Delete var unused
Improve predicate endSequence
=> Improve prolog

client/src/main/scala/it/parttimeteam/model/game/GameServiceImpl.scala, client/src/main/scala/it/parttimeteam/model/game/RemoteGameActor.scala, client/src/test/scala/it/parttimeteam/model/game/RemoteGameActorSpec.scala, commons/src/main/scala/it/parttimeteam/messages/GameMessage.scala, server/src/main/scala/it/parttimeteam/match/GameMatchManager.scala
remove unused DrawCard message and related code
=> Server refactoring, in progress
